Support for Vapor 4
brokenhandsio/fluent-postgis pull request #4
Opened 2022-04-26 16:25 UTC by PoshAlpaca

2022-05-02 12:05 UTC, PoshAlpaca commented
@0xTim  ready for review 🎉

2022-05-02 16:34 UTC, 0xTim requested changes
Great work! Few comments and things that can be updated. Some other things to look at are:
* use async/await throughout the tests assuming it's available to us. Updating the manifest to 5.5 and macOS 12 will help
* we don't have any CI any more, we should set up GH actions to run the tests to make sure things work

2022-05-02 16:34 UTC, 0xTim commented on Package.swift
> +// swift-tools-version:5.1
Let's just set this to 5.5 to make life easier

2022-05-02 16:34 UTC, 0xTim commented on Package.swift
> +       .macOS(.v10_15)
Let's do v12 to allow us to add async/await stuff easily if we want to

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +.package(url: "https://github.com/rabc/fluent-postgis.git", .branch("vapor_4"))
Let's set this for the Broken Hands fork set up

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +PostGIS support for [fluent-postgres-driver](https://github.com/vapor/fluent-postgres-driver) and [Vapor 4](https://github.com/vapor/vapor)
Let's add a sentence about it being a fork of the PostGIS package that provides geographic support on top of the geometric support from the upstream repo

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +    @ID(custom: "id", generatedBy: .database)
We might as well make this a UUID as that's the default in Fluent

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +            .field("id", .int, .identifier(auto: true))
Again UUID like the model

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +try UserLocation.query(on: conn).filterGeometryDistanceWithin(\.$location, user.location, 1000).all().wait()
We define a search location but don't actually use it

2022-05-02 16:34 UTC, 0xTim commented on README.md
> +let searchLocation = GeometricPoint2D(x: 1, y: 2)
Let's use a better lat/lon for this, something like Buckingham Palace etc

2022-05-02 16:34 UTC, 0xTim commented on Sources/FluentPostGIS/Queries/QueryBuilder+Contains.swift
> +       ///
Indentation seems off here in the diff

2022-05-02 16:34 UTC, 0xTim commented on Sources/FluentPostGIS/Support/EnablePostGISMigration.swift
> +    public init() {}
Just double check the name of the migration is computed to be the same in Vapor 3 and Vapor 4 to make sure we don't try to run this again

2022-05-02 16:34 UTC, 0xTim commented on Tests/FluentPostGISTests/GeometryTests.swift
> +        _ = try user.save(on: conn).wait()
If async/await is available to us here we should use it

2022-05-02 16:34 UTC, 0xTim commented on Tests/FluentPostGISTests/GeometryTests.swift
>          XCTAssertEqual(all.count, 1)
a/a if possible

2022-05-02 16:34 UTC, 0xTim commented on Tests/FluentPostGISTests/GeometryTests.swift
> +        _ = try user.save(on: conn).wait()
`save()` returns a `Void` so the `_` can be removed

2022-05-02 16:34 UTC, 0xTim commented on Tests/FluentPostGISTests/XCTestManifests.swift
> +        ("testGeometryCollection", testGeometryCollection),
Let's delete this file and rely on test discovery instead (assuming it works with the subclassing!)

2022-05-02 22:55 UTC, PoshAlpaca commented
@0xTim Thanks for the feedback! Can you take a look again?

2022-05-02 23:03 UTC, PoshAlpaca commented
Also, I was thinking to extend `DatabaseSchema.DataType` with static properties so that fields in migrations can be declared like so:

```swift
.field("location", .geometricPoint2D)
```

instead of:

```swift
.field("location", GeometricPoint2D.dataType)
```

What do you think?

2022-05-03 00:38 UTC, 0xTim commented
@PoshAlpaca yep I think that's a great idea to provide a cleaner API

2022-05-03 00:39 UTC, 0xTim requested changes
Looking great! Last couple of changes just to CI then we're good. We should have CI passing in this PR

And let's add the data type stuff as well if it's simple

2022-05-03 00:39 UTC, 0xTim commented on .github/workflows/ci.yml
> +- push
We should add pull request here as well

2022-05-03 00:39 UTC, 0xTim commented on .github/workflows/ci.yml
> +    - run: swift test --enable-test-discovery
Don't need test discovery that's default since 5.4

2022-05-03 12:04 UTC, 0xTim approved these changes
Looks great! Might need to tweak the `on` section of CI to get it to run or wait until it's merged. Happy to merge however and fix in another PR if necessary

2022-05-03 13:32 UTC, merged